import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav className="border-b">
            <ul className="max-w-7xl mx-auto flex justify-between items-center py-4">
              <Link href="/">
                <p href="#">Home</p>
              </Link>

              <Link href="/request-memoization">
                <p>Request Memoization</p>
              </Link>
              <Link href="/data-cache">
                <p>Data Cache</p>
              </Link>
              <Link href="/full-route-cache">
                <p>Full Route Cache</p>
              </Link>
              <Link href="/route-cache">
                <p>Route Cache</p>
              </Link>
            </ul>
          </nav>
        </header>
        <main className="max-w-7xl mx-auto mt-10">{children}</main>
      </body>
    </html>
  );
}
